version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel_app_dev
    ports:
      - "${APP_PORT:-8000}:9002"
    volumes:
      - ./:/var/www
    env_file:
      - .env
    depends_on:
      - redis
    extra_hosts: # ⬅️ tambahin ini
      - "host.docker.internal:host-gateway"

  vite:
    image: node:20
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    command: sh -c "npm install && npx vite --host 0.0.0.0 --port 5174"
    ports:
      - "5174:5174"
    environment:
      - CHOKIDAR_USEPOLLING=true

  redis:
    image: redis:alpine
    container_name: laravel_redis_dev
    ports:
      - "6379:6379"

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel_queue_dev
    command: php artisan queue:work --sleep=3 --tries=3 --verbose
    volumes:
      - ./:/var/www
    depends_on:
      - app
      - redis
    extra_hosts: # ⬅️ tambahin ini juga
      - "host.docker.internal:host-gateway"

  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - app
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "9002:8080"

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel_scheduler_dev
    command: sh /var/www/docker/cron/laravel-cron
    volumes:
      - ./:/var/www
    depends_on:
      - app
    extra_hosts: # ⬅️ dan ini juga
      - "host.docker.internal:host-gateway"

  artisan:
    build:
      context: .
      dockerfile: docker/Dockerfile.dev
    container_name: laravel_artisan_dev
    working_dir: /var/www
    entrypoint: ["php", "artisan"]
    volumes:
      - ./:/var/www
    depends_on:
      - app
