version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: laravel_app_prod
    restart: always
    env_file:
      - .env
    volumes: []

  nginx:
    image: nginx:stable-alpine
    container_name: laravel_nginx_prod
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/public
    depends_on:
      - app

  redis:
    image: redis:alpine
    container_name: laravel_redis_prod
    restart: always
    ports:
      - "6379:6379"

  queue:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: laravel_queue_prod
    command: php artisan queue:work --sleep=3 --tries=3 --verbose
    depends_on:
      - app
      - redis

  scheduler:
    build:
      context: .
      dockerfile: docker/Dockerfile.prod
    container_name: laravel_scheduler_prod
    command: sh /var/www/docker/cron/laravel-cron
    depends_on:
      - app
